import type { Metadata } from "next";
import { Mali } from "next/font/google";
import "./globals.css";
import Providers from "@/containers/providers";
import Navbar from "@/components/navbar";


const mali = Mali({
  subsets: ["latin"],
  variable: "--font-mali",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "งานแต่งงาน",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${mali.variable} font-hurricane flex flex-col bg-gray-50
       text-gray-950 relative`}
      >
        <div
          className="bg-[#adeff6] absolute top-[-6rem] flex-1 -z-[10] right-[11rem] h-[31.25rem] w-[31.25rem] 
        rounded-full blur-[10rem] sm:w-[68.75rem]`"
        />

        <div
          className="bg-[#8474ff] absolute top-[-1rem] -z-[10] flex-1 left-[-35rem] h-[31.25rem] w-[50rem] 
        rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]
        `"
        />
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
